### ISSUE TITLE
Remove hard-coded Dutch labels

### ISSUE THREAD

**Issue by bertoost** [metaclass-nl/MetaclassAuthenticationGuardBundle#15]
As far I could see there are a couple of Dutch labels inside the "GuardStatsController" which in my opinion not should be there. Using Translations is a better approach I think.

**Comment by metaclass-nl** [comment]
solved in v0.3.1 (Symfony >=2.3, <=2.6)
#TODO: merge in master, test with Symfony 2.6, 2.7, 2.8, 3.0

**Comment by metaclass-nl** [comment]
merged
