### ISSUE TITLE
Missing used MenuItem package/dependency?

### ISSUE THREAD

**Issue by bertoost** [metaclass-nl/MetaclassAuthenticationGuardBundle#16]
The "guard" routing related stuff is requiring a MenuItem which is not included.

```
use Metaclass\CoreBundle\Menu\MenuItem;
```

GuardStatsController.php line 12 and 257

**Comment by metaclass-nl** [comment]
Also Resources/views/Guard/statistics.html.twig extends MetaclassCoreBundle::layout.html.twig. This code is not yet working without that bundle, should have made a development brache for that.

**Comment by metaclass-nl** [comment]
- removed dependency StatisticsController of MetaclassCoreBundle MenuItem
- statistics.html.twig
    . factored out statistics_content.html.twig
    . changed dependency of MetaclassCoreBundle::layout.html.twig to base.html.twig
    . removed view icon specific to bootstrap layout
    . added hyperlinks to history and byUsername
- GuardStatsController actions now use template configuration parameter metaclass_auth_guard.statistics.template
- services.yml now defines default for metaclass_auth_guard.statistics.template
