### ISSUE TITLE
Default configuration set without adding to config.yml

### ISSUE THREAD

**Issue by bertoost** [metaclass-nl/MetaclassAuthenticationGuardBundle#17]
As other bundles;
The default configuration should not be in the app/config/config.yml. Only those you want to override.
Other bundles also works like this.

**Comment by metaclass-nl** [comment]
solved in v0.3.1 (Symfony >=2.3, <=2.6)
#TODO: merge in master, test with Symfony 2.6, 2.7, 2.8, 3.0

**Comment by metaclass-nl** [comment]
merged
