### ISSUE TITLE
why not use doctrine ORM to create table structure?

### ISSUE THREAD

**Issue by videni** [metaclass-nl/MetaclassAuthenticationGuardBundle#23]
I am wondering why not use doctrine ORM to create table structure, this can make upgrade  simpler.

**Comment by metaclass-nl** [comment]
Hello Vidy,

The way the tresholds governor uses the database makes ORM not very usefull for querying and updating the data, therefore i did not develop the Entities that would require. Furthermore, when i have time i want to make the packages independent of doctrine (DBAL). 

But i agree that for those who are familiar with Doctrine it could be usefull to have a separate package for generation of the table structure, especially if you want to use a different database. You can make such a package yourself if you like. If you don't, thanks for sharing the idea!

If anyone would like such a package please leave a comment here.

**Comment by videni** [comment]
@metaclass-nl, thanks for your detail explanation. this can be closed.
